---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: be-python
  labels:
    app: backend
    lang: python
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: backend
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: backend
        lang: python
    spec:
      containers:
      - image: ocp-demo:golang
        imagePullPolicy: Always
        name: backend
        resources:
          limits:
            memory: 64Mi
            cpu: 500m
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - backend
      from:
        kind: ImageStreamTag
        name: ocp-demo:python
    type: ImageChange
