apiVersion: v1
kind: DeploymentConfig
metadata:
  name: be-rust
  labels:
    app: backend
    lang: rust
spec:
  replicas: 1
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
        lang: rust
    spec:
      restartPolicy: Always
      containers:
      - name: backend
        image: image-registry.openshift-image-registry.svc:5000/ocp-demo/ocp-demo:rust
        resources:
          limits:
            cpu: 500m
            memory: 64Mi
        imagePullPolicy: Always
  strategy:
    type: Rolling
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - backend
      from:
        name: ocp-demo:rust
        kind: ImageStreamTag
