apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
spec:
  #host: ocp-demo.apps.ocp4.rhpg.org
  path: /
  to:
    kind: Service
    name: ocp-demo
  port:
    targetPort: 3030
  tls:
    termination: edge
