apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
- be-golang/build-config.yaml
- fe-node/build-config.yaml
- be-python/build-config.yaml
- be-rust/build-config.yaml
- route-be.yaml
- route-fe.yaml
namespace: ocp-demo