apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "be-golang"
spec:
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      name: 'ocp-demo:golang'
      kind: ImageStreamTag
  runPolicy: "Serial"
  source:
    type: Dockerfile
    contextDir: /
    dockerfile: |-
      FROM golang as builder
      RUN apt-get update && apt-get install git make gcc linux-libc-dev\
          && mkdir -p /build/monorepo

      WORKDIR /build/monorepo
      RUN git clone https://github.com/mancubus77/ocp-demo-monorepo /build/monorepo/ \
          && cd /build/monorepo/be-golang \
          && go build -o be-golang

      FROM golang
      RUN mkdir -p /app \
          && mkdir -p /data \
          && apt-get update && apt-get install gcc
      WORKDIR /app
      COPY --from=builder /build/monorepo/be-golang/be-golang .
      ENTRYPOINT ["/app/be-golang"]
  triggers:
  - type: "ConfigChange"
  - type: ImageChange
