---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: be-golang
  labels:
    app: backend
    lang: golang
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: backend
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: backend
        lang: golang
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ocp-demo/ocp-demo:golang
        imagePullPolicy: Always
        name: backend
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - backend
      from:
        kind: ImageStreamTag
        name: ocp-demo:golang
    type: ImageChange