apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo
resources:
# Infra Tasks
- infra/image-builder.yaml
# Golang
- be-golang/build-config.yaml
- be-golang/deployment-config.yaml
# Python
- be-python/build-config.yaml
- be-python/deployment-config.yaml
# Rust
- be-rust/build-config.yaml
- be-rust/deployment-config.yaml
# Frontend
- fe-node/build-config.yaml
- fe-node/deployment-config.yaml
- fe-node/service.yaml
# Infra Tasks
- infra/route-be.yaml
- infra/route-fe.yaml
- infra/service.yaml
