---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: fe-node
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/mancubus77/ocp-demo-monorepo'
      ref: main
    contextDir: /fe-node
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'ocp-demo:fe-node'