apiVersion: v1
kind: DeploymentConfig
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: image-registry.openshift-image-registry.svc:5000/ocp-demo/ocp-demo:golang
        env:
        - name: "URL"
          value: "http://ocp-demo:3030/v1/whoami"
        resources:
          limits:
            cpu: 500m
            memory: 2048Mi
        imagePullPolicy: Always
  strategy:
    type: Rolling
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - frontend
      from:
        name: ocp-demo:fe-node
        kind: ImageStreamTag
